name: The Rust Programming Language
stable: "1.28.0"
stable_date: "2018-08-02"
stable_blog: "https://blog.rust-lang.org/2018/08/02/Rust-1.28.html"
stable_full_version: "rustc 1.28.0 (9634041f0 2018-07-30)"
beta: "1.29"
beta_date: "2018-09-13"
nightly: "1.30"
channels:
  - name: "stable"
    vers: "1.28.0"
    package: "1.28.0"
  - name: "beta"
    vers: "1.29"
    package: "beta"
  - name: "nightly"
    vers: "1.30"
    package: "nightly"
