name: The Rust Programming Language
stable: "1.22.1"
stable_date: "2017-11-22"
stable_blog: "https://blog.rust-lang.org/2017/11/22/Rust-1.22.html"
stable_full_version: "rustc 1.22.1 (05e2e1c414 2017-11-22)"
beta: "1.23"
beta_date: "2017-11-21"
nightly: "1.24"
channels:
  - name: "stable"
    vers: "1.22.1"
    package: "1.22.1"
  - name: "beta"
    vers: "1.23"
    package: "beta"
  - name: "nightly"
    vers: "1.24"
    package: "nightly"
