name: The Rust Programming Language
stable: "1.30.0"
stable_date: "2018-10-25"
stable_blog: "https://blog.rust-lang.org/2018/10/25/Rust-1.30.0.html"
stable_full_version: "rustc 1.30.0 (da5f414c2 2018-10-24)"
beta: "1.31"
beta_date: "2018-12-06"
nightly: "1.32"
channels:
  - name: "stable"
    vers: "1.30.0"
    package: "1.30.0"
  - name: "beta"
    vers: "1.31"
    package: "beta"
  - name: "nightly"
    vers: "1.32"
    package: "nightly"
