name: The Rust Programming Language
stable: "1.29.0"
stable_date: "2018-09-13"
stable_blog: "https://blog.rust-lang.org/2018/09/13/Rust-1.29.html"
stable_full_version: "rustc 1.29.0 (aa3ca1994 2018-09-11)"
beta: "1.30"
beta_date: "2018-10-25"
nightly: "1.31"
channels:
  - name: "stable"
    vers: "1.29.0"
    package: "1.29.0"
  - name: "beta"
    vers: "1.30"
    package: "beta"
  - name: "nightly"
    vers: "1.31"
    package: "nightly"
