name: The Rust Programming Language
stable: "1.27.2"
stable_date: "2018-07-20"
stable_blog: "https://blog.rust-lang.org/2018/07/20/Rust-1.27.2.html"
stable_full_version: "rustc 1.27.2 (58cc626de 2018-07-18)"
beta: "1.28"
beta_date: "2018-08-02"
nightly: "1.29"
channels:
  - name: "stable"
    vers: "1.27.2"
    package: "1.27.2"
  - name: "beta"
    vers: "1.28"
    package: "beta"
  - name: "nightly"
    vers: "1.29"
    package: "nightly"
