name: The Rust Programming Language
stable: "1.29.2"
stable_date: "2018-10-12"
stable_blog: "https://blog.rust-lang.org/2018/10/12/Rust-1.29.2.html"
stable_full_version: "rustc 1.29.2 (17a9dc751 2018-10-05)"
beta: "1.30"
beta_date: "2018-10-25"
nightly: "1.31"
channels:
  - name: "stable"
    vers: "1.29.2"
    package: "1.29.2"
  - name: "beta"
    vers: "1.30"
    package: "beta"
  - name: "nightly"
    vers: "1.31"
    package: "nightly"
