name: The Rust Programming Language
stable: "1.24.0"
stable_date: "2018-02-15"
stable_blog: "https://blog.rust-lang.org/2018/02/15/Rust-1.24.html"
stable_full_version: "rustc 1.24.0 (4d90ac38c 2018-02-12)"
beta: "1.24"
beta_date: "2018-03-29"
nightly: "1.25"
channels:
  - name: "stable"
    vers: "1.24.0"
    package: "1.24.0"
  - name: "beta"
    vers: "1.24"
    package: "beta"
  - name: "nightly"
    vers: "1.25"
    package: "nightly"
