name: The Rust Programming Language
stable: "1.25.0"
stable_date: "2018-03-29"
stable_blog: "https://blog.rust-lang.org/2018/03/29/Rust-1.25.html"
stable_full_version: "rustc 1.25.0 (84203cac6 2018-03-25)"
beta: "1.26"
beta_date: "2018-05-10"
nightly: "1.27"
channels:
  - name: "stable"
    vers: "1.25.0"
    package: "1.25.0"
  - name: "beta"
    vers: "1.26"
    package: "beta"
  - name: "nightly"
    vers: "1.27"
    package: "nightly"
