name: The Rust Programming Language
stable: "1.29.1"
stable_date: "2018-09-25"
stable_blog: "https://blog.rust-lang.org/2018/09/25/Rust-1.29.1.html"
stable_full_version: "rustc 1.29.1 (b801ae664 2018-09-20)"
beta: "1.30"
beta_date: "2018-10-25"
nightly: "1.31"
channels:
  - name: "stable"
    vers: "1.29.1"
    package: "1.29.1"
  - name: "beta"
    vers: "1.30"
    package: "beta"
  - name: "nightly"
    vers: "1.31"
    package: "nightly"
