name: The Rust Programming Language
stable: "1.24.1"
stable_date: "2018-03-01"
stable_blog: "https://blog.rust-lang.org/2018/02/15/Rust-1.24.html"
stable_full_version: "rustc 1.24.1 (d3ae9a9e0 2018-02-27)"
beta: "1.25"
beta_date: "2018-03-29"
nightly: "1.26"
channels:
  - name: "stable"
    vers: "1.24.1"
    package: "1.24.1"
  - name: "beta"
    vers: "1.25"
    package: "beta"
  - name: "nightly"
    vers: "1.26"
    package: "nightly"
